apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add our new, correct configmap.yaml back to the resources
resources:
- namespace.yaml
- rbac.yaml
- workflow.yaml
- configmap.yaml
- rclone-config.yaml
- sealed-secrets/iris-demo-ghcr.yaml
- sealed-secrets/iris-demo-minio.yaml
- sealed-secrets/iris-demo-mlflow.yaml

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: iris-demo
    app.kubernetes.io/part-of: ml-platform
    app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  app.kubernetes.io/version: "v0.2.0"
