# manifests/patches/minio-credentials-patch.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials-wf
  namespace: argowf
stringData:
  RCLONE_CONFIG_S3_TYPE: "s3"
  RCLONE_CONFIG_S3_PROVIDER: "Minio"
  RCLONE_CONFIG_S3_ENV_AUTH: "false"
  RCLONE_CONFIG_S3_ENDPOINT: "http://minio.minio.svc.cluster.local:9000"