apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - seldon-deploy-rbac.yaml 

patches:
- path: allow-taskresults.yaml
  target:
    kind: Role
    name: workflow-role

patchesJson6902:
- target:
    group:   argoproj.io
    version: v1alpha1
    kind:    Workflow
    name:    iris-demo
  path: resource-limits.json

labels:
  - includeSelectors: false
    pairs:
      environment: dev
