apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-seldondeployments
  namespace: argowf
rules:
- apiGroups:
  - machinelearning.seldon.io
  resources:
  - seldondeployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-deploy-seldondeployments
  namespace: argowf
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: iris-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy-seldondeployments