# Save this as demo-iris-pipeline-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-mlops-demo
  namespace: argocd  # This is correct - ArgoCD apps live in argocd namespace
spec:
  project: default
  source:
    repoURL: https://github.com/jtayl222/homelab-mlops-demo.git
    targetRevision: main
    path: demo_iris_pipeline  # <- directory that contains workflow.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argowf  # Change this to argowf - where workflows run
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
