---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: iris-demo-ghcr
  namespace: iris-demo
spec:
  encryptedData:
    .dockerconfigjson: AgCYcgNjrW0+9B668Ek+Epg7DS8FW3iK6BAo5kJuPB9LFvRnwI07Sz8dMJgITl3MShZERau4KVQ3R7n/58mELhgtHnKcfXTHwGolX5uOa2WE33Ki8Xb++hnq4ThAf4yEZxcfGkm5Iu4UMne4wCp/xkGIN6bsQ7aa6lklqQ55r+vFlSVwHOtfvX6TnVvrfD7aawdnJZEEr+cMvFPVlalTgcxQKgVurPpkXJ7OZxRfEGCtysfjctduOdS5jg+2U00cQz9xn0GFRCigfeL3FotGza48pfAVWrkCJ3pbYv0KzGf/FlG8CcPpi7z4BiawPxrjfO/Wv8VJXl29xlDvBJewiuD8pCgcUS6NyAty4ss2IYAShs98XwTZtVympzcsoSw2qLoGBoe48M/I/iLreiDZtBzvIMrgm3iQpdbmheab2i0pzsZTct8gQjxo+sn2kcE2kyS5iNCpJTJ14yQz6LxGfSRrEoxxatE3NdDgIb6mkNL9MEoBnyaiO6EORKDhxp3yNiJLOknieOiXUIFUK9vl10d2GB0mWeNNN9ob6dNqnJq1XJmd4BrGzYF18R7hKRcCTKjurY+NCsO3Td5ianMKTM5tohJ0G1f5NxwCOVw9uovrqbgd00EwRAR7Af/czwpW8uc5wVXw+5wP/42Xp3jc6+biT/budZJ8PmXcXLhLN/p7e+cznw0D9R6U5bOPCmAZCaaMnJFGxpeGNHunWod7v3ewKypJaq1DtBE9uPwDEW9anYe9lihOwM7vAmol7NBM6B/VvhwvElQoUkv5uaCs3awwOHM7wWnZKxw4e4dZTPhBjssI/n5dyA08WV1UVqn0a0wpq4nk9xTm3pUkiRsLVnbTJDyaiBS2usldRQtmcFFPZOVuYbfeuh/C9B+iR4NbDjpkDITRjCW0EpW3Z6dqMLSZXgy3NapSQMvkGKN1D+OKj+lfwWoBBPmBztxTWX8BjZHJVISVgobfxD30lCk4aVaV8Kw9vQB70TUiCsgodTkI
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: iris-demo-ghcr
      namespace: iris-demo
    type: kubernetes.io/dockerconfigjson
