apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service-account.yaml
- role.yaml
- rolebinding.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: homelab-mlops
    app.kubernetes.io/component: rbac
