apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-binding
  namespace: argowf
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: argowf
roleRef:
  kind: Role
  name: workflow-role
  apiGroup: rbac.authorization.k8s.io
