apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: argowf-dev

namePrefix: dev-

patches:
  - path: app-config-patch.yaml
    target:
      kind: ConfigMap
      name: app-config

labels:
  - pairs:
      environment: development
