apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argowf

resources:
- ../../base

labels:
- includeSelectors: true
  pairs:
    environment: production
    security.level: high

commonAnnotations:
  deployment.environment: production
  managed.by: kustomize
