apiVersion: v1
kind: Secret
metadata:
  name: rclone-config
  namespace: argowf
type: Opaque
stringData:
  rclone.conf: |
    [s3]
    type = s3
    provider = Minio
    env_auth = false
    endpoint = http://minio.minio.svc.cluster.local:9000
    access_key_id = ${MINIO_ACCESS_KEY}
    secret_access_key = ${MINIO_SECRET_KEY}
    region = us-east-1